title: Isa K. Chau # your name (or website title) here
title2: Data Scientist
logo: "/images/headshots/utah-pic-3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm a recent graduate of the Master of Information and Data Science program at UC Berkeley School of Information looking to begin my data science career, with particular interest in the fields of health, education, and fintech. My prior professional experience includes jobs in media production, special education, emergency medicine, and athletic training.
  <br><br>
  In my spare time I coach Olympic weightlifting and make pizza (not simultaneously). I am a proud East Bay resident since 2014.
  <br><br>
  
  <a href='https://github.com/ikchau/ikchau.github.io/raw/master/pdf/Isa%20Chau%20Resume%20Jan%202021%20v2%20github.pdf'>
  Click to download my resume <img src="images/PDF_24.png?raw=true">
  </a>
  
  <br><br>
  <a href='https://www.linkedin.com/in/isa-chau'><img src="images/LinkedIn-Logos/LinkedIn-Logos/LI-Logo.png?raw=true" height="25">
  </a>
  
  <a href="https://github.com/ikchau"><img src="images/GitHub_Logo.png?raw=true" height="30"></a></p>
  <br><br>
  <small><br>Hosted on GitHub Pages &mdash; Theme by <a href="https://github.com/orderedlist">orderedlist<br><br></a></small>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
