title: Isa K. Chau # your name (or website title) here
logo: "/images/headshots/garbage-day-headshot-torso.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm a recent graduate of the Master of Information and Data Science program at UC Berkeley School of Information looking to begin my data science career, with particular interest in the fields of health, education, and fintech. My prior professional experience includes jobs in media production, special education, emergency healthcare, and athletic training.
  <br><br>
  In my spare time I coach Olympic weightlifting and make pizza (not simultaneously). I am a proud East Bay resident since 2014.
  <br><br><br>
  <a href="https://www.linkedin.com/in/isa-chau/">View My LinkedIn Profile</a> 
  
  <a href='https://www.linkedin.com/in/isa-chau'>
  <img src="images/LinkedIn-Logos/LinkedIn-Logos/LI-Logo.png?raw=true" width="30" height="30">
  </a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
